# fly.toml app configuration file generated for personal-blog-app-backend on 2024-02-02T21:44:15-03:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'personal-blog-app-backend'
primary_region = 'ewr'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 512
